// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCzoxXH3bixYjl5v_8SORo2COOwqfNnfM',
    appId: '1:700673000194:android:d63b33dd49b9d3faae781b',
    messagingSenderId: '700673000194',
    projectId: 'chat-4646b',
    storageBucket: 'chat-4646b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCu1pwHzHXfzqqmNektQqGn6UduHbQUzf4',
    appId: '1:700673000194:ios:3429025b17aaf39bae781b',
    messagingSenderId: '700673000194',
    projectId: 'chat-4646b',
    storageBucket: 'chat-4646b.appspot.com',
    androidClientId: '700673000194-c4v88l97blnunknd6okffg1ukhihs9l0.apps.googleusercontent.com',
    iosClientId: '700673000194-cjuvnqpgdkm9g78rprc38ou8r4aodivp.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat',
  );
}
